---
title: "Capstone Project for DA"
author: "DA class"
date: "6/28/2024"
output: html_document
---


## Capstone Project for Data Analysis Class NIIT Benin.

```{r Q1 import libraries}

### Import all the necessary libraries for this project

library(tidyverse)
library(readxl)


```


```{r Q2 import the first csv file}
### import the csv file - athlete_events.csv
athlete <- read.csv(file.choose())
```


```{r }
### show the first 10 records from the dataset

View(head(athlete, 10))
```


```{r }
### show all the columns in the dataset

colnames(athlete)

```


```{r Q3 import the second csv file }
### import the csv file - noc_regions.csv

regions <- read.csv(file.choose())
```


```{r Q3}
### show the first 10 records from the dataset

View(head(regions, 10))
```


```{r Q3 import the second csv file }
### show all the columns in the dataset

colnames(regions)

```




```{r Q4 merge the two datasets}
### merge the two datasets on the common column - NOC, create a 
### new dataframe from the merger
athlete_region <- inner_join(x= athlete, y= regions, by= "NOC")
```




```{r Q5 show the dimension of the dataset }
### show the total number of rows and columns in the merged dataset

dim(athlete_region)

```



```{r}
View(athlete_region)
```


```{r}
colnames(athlete_region)
```


```{r Q6 describe the dataset structure}
### get information about the dataframe using the str() function
str(athlete_region)

```




```{r Q7 show summary statistics}

### show the summary statistics on all columns in the merged 
### dataset 

summary(athlete_region)
```


```{r Q8 check for missing values}
### check for missing values in each of the columns in the 
### dataset.
is.na(athlete_region)


```



```{r Q9 total number of missing values}
### show the total number of null values in each column of the 
### dataset

sum(is.na(athlete_region))

```



```{r Q10 athletes from India and USA}
### show the athletes from the country India or United States
athlete_region %>% 
  filter(region == "USA" | region == "India") %>% 
  group_by(region) %>% 
  summarise(total=n())


### How many are the athletes of both countries 


```



```{r Q11 first and last year captured}
### Using a function show the first and the last years captured
### in the dataset 
View(head(athlete_region, 1))
```


```{r }
View(tail(athlete_region, 1))

```



```{r Q12 show number of athletes each year}
athlete_region %>% 
  group_by(Year) %>% 
  summarise(total=n())


```

```{r}
### show the number of athletes that participated each year
athlete_region %>% 
  group_by(Year) %>% 
  summarise(total=n()) %>% 
  arrange(-total) %>% 
  head(5) %>% 
  ggplot(aes(x=Year, y=total)) + geom_col(aes(y = total), color = "brown", size = 0.6)
```


```{r Q13 top 5 years with highest atheletes }
### show the top 5 years with the highest number of athletes 
### participation
athlete_region %>% 
  group_by(Year) %>% 
  summarize(total = n()) %>% 
  arrange(-total) %>% 
  head(5)
```


```{r }
athlete_region %>% 
  group_by(Year) %>% 
  summarise(total = n()) %>% 
  arrange(-total) %>% 
  head(5) %>% 
  ggplot(aes(x=Year, y= total)) + 
  geom_col(aes(y=total), color = "red", size = 0.6)
  
### visualise this using the column chart



```




```{r Q14 top 10 participating countries}
### show the top 10 countries with the highest participation overall
athlete_region %>% 
  group_by(region) %>% 
  summarise(total = n()) %>% 
  arrange(-total) %>% 
  head(10)

```


```{r }
### visualise the result above using a bar chart in ggplot2, sort from lowest to highest
athlete_region %>% 
  group_by(region) %>% 
  summarise(total= n()) %>% 
  arrange(-total) %>% 
  head(10) %>% 
  ggplot(aes(x = region,y = total, fill = region, )) +
  geom_bar(aes(y = total),stat = "identity", position = "dodge")
+ geom_text(aes( x = region, y = total, label = total), vjust = "inward") +
  coord_flip()





```



```{r Q15 show age distribution}

### Using ggplot2 histogram, show the age distribution of the 
### participating athletes 


```



```{r Q16 winter and summer olympic games}
### show all the winter olympic games
athlete_region %>% 
  filter(Season == "Winter") %>% 
  group_by(Season) %>% 
  summarise(total =n())

```

```{r }
### show all the summer olympic games 
athlete_region %>% 
  filter(Season == "summer") %>% 
  group_by(Season) %>% 
  summarise(total = n())





```


```{r Q17 male and female distribution}
### show the number of male and female participants in the olympics
athlete_region %>% 
  filter(Sex == "M" | Sex == "F") %>% 
  group_by(Sex) %>% 
  summarise(total = n())
```


```{r }
### visualise this using the ggplot2 pie chart
athlete_region %>% 
  filter(Sex == "F") %>% 
  group_by(Sex) %>% 
  summarise(total = n()) %>% 
  ggplot(aes(x = Sex, y = total, fill = Sex, )) + 
  geom_bar(aes(y = total), stat = "identity", position = "dodge") +
  geom_text(aes(x = Sex, y = total, label = total), vjust = "inward")+
  coord_polar()
  




```




```{r Q18 total number of medals each country }
### show the total number of medals won in each country
athlete_region %>% 
  group_by(region, Medal) %>% 
  summarise(total = n())
```


```{r }
### visualize this using the ggplot2 bar chart
athlete_region %>% 
  group_by(region, Medal) %>% 
  summarise(total = n()) %>% 
  ggplot(aes(x = region, y = Medal, fill = region)) +
  geom_bar(aes(y = Medal), stat = "identity", position = "dodge") + geom_text(aes( x = region, y = Medal, label = total),vjust = "inward")






```



```{r Q19 number of female participants }
### show the total number of female participants in each 
### year of the olympics
athlete_region %>% 
  filter(Sex =="F") %>% 
  group_by(Year) %>% 
  summarise(total= n())
```


```{r }
### visualise this using the ggplot2 column chart
athlete_region %>%
  filter(Sex == "F") %>% 
  group_by(Year) %>% 
  summarise(total = n()) %>% 
 ggplot(aes(x = reorder(Year,total), y=total, fill = Year))  + 
  geom_col(aes(y = total), stat = "identity",position = "dodge") + labs(x="Year",y="total",title ="Total Numbers Of Female Participant in Each Year of The Olympics")+ coord_flip() 
  

```




```{r Q20 gold medalist}

### show the gold medalists for the olympics 2000 and their respective countries
athlete_region %>%
  filter(Medal== "Gold" & Year== 2000) %>% 
  group_by(region, Medal) %>%
    summarise(total = n()) %>% 
  arrange(desc(total))




```



```{r Q21 overall top 10 gold medals }
### show the overall top 10 highest gold medals for each country
athlete_region %>%
  filter(Medal == "Gold") %>% 
  group_by(region, Medal) %>% 
  summarise(total = n()) %>% 
  arrange(desc(total)) %>% 
  head(10)

```


```{r Q21}
### visualise this using the column bar chart
athlete_region %>%
  filter(Medal == "Gold") %>% 
  group_by(region, Medal) %>% 
  summarise(total = n()) %>% 
  arrange(desc(total)) %>% 
  head(10) %>%
  ggplot(aes(x =reorder(region, -total), y = total, fill = region, ))  + 
  geom_bar(aes(y = total), stat = "identity",position = "dodge") + labs(x="Region", y= "Medals", title = "Top 10 highest Gold medals for each country") +
  geom_text(aes( x=region, y= total, label = total),vjust ="inward") + coord_flip()





```


```{r Q22 number gold medals won across the years}
athlete_region %>%
  filter(Medal == "Gold") %>% 
  group_by(Year, Medal) %>% 
  summarise(total = n())
```


```{r Q22}
### visualise using ggplot2 geom_line() function the variations in 
### the number of gold medals won from the year 1948 to 2016
athlete_region %>%
  filter(Medal == "Gold", Year>1947) %>% 
  group_by(Year, Medal) %>% 
  summarise(total = n()) %>%
  ggplot(aes(x = Year, y = total)) + geom_line (aes(x= Year, y = total), color = "blue")+
  labs(x="Year", y= "count", title = "variations in number of gold medals won from the year 1948 to 2016") + geom_text(aes(y= total, label = Year),vjust ="inward", size = 2.5)







```



```{r Q23 medals won by Africans}
### Show the number of medals won each by Nigeria, South Africa and Kenya from the year 2010 to 2016
athlete_region %>% 
  filter(region %in% c("Nigeria", "South Africa", "Kenya"), 
         Year>2009, !(is.na(Medal)))%>%
  group_by(region, Year) %>% 
  summarise(total = n())
```


```{r Q23}
### Visualise this using the clustered bar chart.



```




```{r Q24 Nigeria medals 2016}

### Show all the athletes that won medals for Nigeria in the 2016
### olympics and the sports they won them in.
athlete_region %>% 
  filter(region == "Nigeria", Year==2016, !(is.na(Medal))) %>% 
  group_by(Name, Sport) %>% 
  summarise(total = n())



```



```{r Q25 age_bracket medals won}
### show the number of medals won from the year 2000 to 2016 
### by the following age groups

### 10 -19
### 20 - 30
### 31-40
### 41-50
### 51- above
### sort from highest to lowest
athlete_region %>% 
  mutate(Age_bracket = dplyr::case_when(Age<=19 ~ "10-19", Age>19 & Age<=30 ~ "20-30",Age>30 & Age<=40 ~"31-40",Age>40 & Age<=50 ~ "41-50", Age>50 ~"Above 51"),Age_bracket=
           factor(Age_bracket,level=c("10-19","20-30","31-40","41-50","Above 51"))) %>% 
  filter(Year>1999,!(is.na(Medal))) %>% 
  group_by(Age_bracket) %>% 
  summarise(total=n())
```


```{r Q25 age_bracket medals won}
# visualise your result using ggplot2 column chart
athlete_region %>% 
  mutate(Age_bracket = dplyr::case_when(Age<=19 ~ "10-19", Age>19 & Age<=30 ~ "20-30",Age>30 & Age<=40 ~"31-40",Age>40 & Age<=50 ~ "41-50", Age>50 ~"Above 51"),Age_bracket=
           factor(Age_bracket,level=c("10-19","20-30","31-40","41-50","Above 51"))) %>% 
  filter(Year>1999,!(is.na(Medal))) %>% 
  group_by(Age_bracket) %>% 
  summarise(total=n()) %>% 
  ggplot(aes(x= reorder(Age_bracket, -total),y=total,fill =Age_bracket)) + geom_col(aes(y = total),position = "dodge") +labs(x= "Age_bracket",y ="count",title = "Medals won from 2000-2016 by Age grade")+ geom_text(aes(y=total,label=total),vjust="inward")


```



```{r Q26 USA wins 2016}

### show all the athletes that won medals for USA in the year 
### 2016 and the sports that they won them in.
athlete_region %>% 
  filter(region == "USA", Year==2016, !(is.na(Medal))) %>% 
  group_by(Name, Sport) %>% 
  summarise(total = n())



```



```{r Q27 number of sports 2000 }

### show the total number of unique sports that athletes participated ### in olympics 2000
athlete_region %>% 
  filter(Year==2000) %>% 
  group_by(Sport) %>% 
  summarise(total = n())





```


```{r Q28 sports with highest medals}
### show the top 5 countries that won the highest gold medals 
### in the year 2016
athlete_region %>% 
  filter(Medal== "Gold", Year==  2016) %>% 
  group_by(region) %>% 
  summarise(total = n())
```


```{r Q28}
### visualise this using the ggplot bar chart
athlete_region %>% 
  filter(Medal== "Gold", Year==  2016) %>% 
  group_by(region) %>% 
  summarise(total = n()) %>%
  arrange(desc(total)) %>% 
  head(20) %>% 
ggplot(aes(x = reorder(region,-total), y=total, fill = region))  + 
  geom_bar(aes(y = total), stat = "identity",position = "dodge") +
  geom_text(aes( x=region, y= total, label = total),vjust ="inward")+coord_flip()


```


```{r Q29 top 5 countries 2016} 
### show the the top 5 countries that won the highest medals overall 
###in the year 2016, sort from highest to lowest
athlete_region %>% 
  filter(Year==  2016, !(is.na(Medal))) %>% 
  group_by(region) %>% 
  summarise(total = n()) %>% 
  arrange(-total) %>% 
  head(5)
```


```{r Q29} 
### visualise this using the ggplot bar chart, keeping the sort order

athlete_region %>% 
  filter(Year==  2016, !(is.na(Medal))) %>% 
  group_by(region) %>% 
  summarise(total = n()) %>% 
  arrange(-total) %>% 
  head(5) %>% 
  ggplot(aes(x = reorder (region, -total), y= total, fill = region, ))  + 
  geom_bar(aes(y = total), stat = "identity",position = "dodge") +
  geom_text(aes( x=region, y= total, label = total),vjust ="inward") + coord_flip()


```






```{r Q30 no wins}
### show the countries that did not win any medals at the olympics 
### 2016
athlete_region %>% 
  filter(Year==  2016, is.na(Medal))%>%
  group_by(region) %>% 
  summarise(total = n())

```


```{r Q30}
### visualise this using the ggplot2 bar chart
athlete_region %>% 
  filter(Year==  2016, is.na(Medal))%>%
  group_by(region) %>% 
  summarise(total = n()) %>%
  arrange(desc(total)) %>% 
  head(20) %>% 
 ggplot(aes(x = reorder (region, -total), y= total, fill = region, ))  + 
  geom_bar(aes(y = total), stat = "identity",position = "dodge") + labs(x = "region", y = "total", title = "countries without medals") +
  geom_text(aes( x=region, y= total, label = total),vjust ="inward") + coord_flip()

```

